added non-versioned dependency list support to bsync-checkgraph

diff --git a/src/bsync-checkgraph b/src/bsync-checkgraph
--- a/src/bsync-checkgraph
+++ b/src/bsync-checkgraph
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #
-# Usage: $0
+# Usage: $0 <output dir> <local>
 #Tests the structure of the build graph on build.sync file in the current repo
 #
 #It starts by adding all elements in the local build.sync file to the internal table.
@@ -31,23 +31,21 @@ while IFS= read -r line;do
   if [[ $(echo $cline | wc -w) -ge 1 ]]; then
     if [[ $(echo $cline | wc -w) -ge 2 ]]; then
       read repo pversion <<<"$(echo $cline | cut -d ' ' -f1) $(echo $cline | cut -d ' ' -f2)"
-      #echo $repo $pversion
+      tversion=$(git -C $BSYNCDIR/$repo rev-parse $pversion 2>/dev/null)
+      if test $? -ne 0; then
+        echo "error:Invalid Node <$repo - $pversion>. abort" >&2
+        exit 1
+      fi
+      #echo $repo $tversion
     else
-      read repo pversion <<<"$(echo $cline | cut -d ' ' -f1) HEAD"
-      #echo $repo $pversion
+      read repo tversion <<<"$(echo $cline | cut -d ' ' -f1) local"
+      #echo $repo $tversion
     fi
     #Translation Phase
     #Support for single Vault only
-    trepo=$BSYNCDIR/$repo
-    tversion=$(git -C $BSYNCDIR/$repo rev-parse $pversion 2>/dev/null)
-    if test $? -eq 0; then
-      Trepo[$index]=$trepo;
-      Tver[$index]=$tversion;
-      ((index++))
-    else
-      echo "error:Invalid Node <$repo - $pversion>. abort" >&2
-      exit 1
-    fi
+    Trepo[$index]=$BSYNCDIR/$repo
+    Tver[$index]=$tversion;
+    ((index++))
   fi
 done <<< "$bs"
 return 0
@@ -58,8 +56,14 @@ declare -a Tver
 declare -a skiptable
 index=0
 #add parent repository to Table
-Trepo[$index]=$(git rev-parse --show-toplevel)
-Tver[$index]=$(git rev-parse HEAD)
+if test "$2" == "local";then
+#only works if executed at repo root
+  Trepo[$index]=$(pwd)
+  Tver[$index]="local"
+else
+  Trepo[$index]=$(git rev-parse --show-toplevel)
+  Tver[$index]=$(git rev-parse HEAD)
+fi
 ((index++))
 for ((i=0;i<index;i++)); do
   exists=0
@@ -69,22 +73,28 @@ for ((i=0;i<index;i++)); do
         exists=1
         skiptable[$i]=1;
       else
-        echo -e "error:Ambiguous Node (${Trepo[$j]}):\n${Tver[$j]}\n${Tver[$i]}\nabort" >&2
+        echo -e "error:Ambiguous Node (${Trepo[$j]}):\n${Tver[$j]} - ${Tver[$i]}\nabort" >&2
         exit 1
       fi
     fi
   done
   if test $exists -eq 0; then
   #detect if build.sync file exists in its default directories
-    bs=$(git -C ${Trepo[$i]} show ${Tver[$i]}:build.sync 2>/dev/null) \
-    || bs=$(git -C ${Trepo[$i]} show ${Tver[$i]}:src/build.sync 2>/dev/null) \
-    && add2table
+    if test ${Tver[$i]} == "local"; then
+      bs=$(cat ${Trepo[$i]}/build.sync 2>/dev/null) \
+      || bs=$(cat ${Trepo[$i]}/src/build.sync 2>/dev/null) \
+      && add2table
+    else
+      bs=$(git -C ${Trepo[$i]} show ${Tver[$i]}:build.sync 2>/dev/null) \
+      || bs=$(git -C ${Trepo[$i]} show ${Tver[$i]}:src/build.sync 2>/dev/null) \
+      && add2table
+    fi
   fi
 done
 #output to file if $1 is an existing directory
 #filename is the sha1 value of the parent node
 #overwrites file
-if test $# -eq 1 -a -d "$1";then
+if test $# -ge 1 -a -d "$1";then
   rm -rf ${1}/${Tver[0]}
   for ((i=1;i<index;i++));do
     if [[ ${skiptable[$i]} -ne 1 ]]; then
